name: Send a Tweet
on: [push]
jobs:
  tweet:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.head_commit.message, 'enh(post)') }}
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          # status: "Hi, this is a test!"
          status: ${{ github.event.head_commit.message }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
